apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-container
        image: nom_de_votre_image:tag  # Remplacez par le nom et le tag de votre image Docker
        ports:
        - containerPort: 8080
